// Simple GraphQL client for the 'new' example
// In a real app, you'd use the Zeus client generated by Axolotl

async function graphqlFetch<T>(query: string, variables?: Record<string, unknown>): Promise<T> {
  const response = await fetch('/graphql', {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
    },
    body: JSON.stringify({ query, variables }),
  });

  const json = await response.json();
  if (json.errors) {
    throw new Error(json.errors[0]?.message || 'GraphQL Error');
  }
  return json.data;
}

export const gql = {
  query: {
    hello: () => graphqlFetch<{ hello: string }>('query { hello }'),
  },
  mutation: {
    echo: (message: string) =>
      graphqlFetch<{ echo: string }>(`mutation Echo($message: String!) { echo(message: $message) }`, {
        message,
      }),
  },
};
