// GraphQL client using Zeus generated by Axolotl
// The Zeus client is located in ../src/zeus/

import { Chain } from '../../src/zeus/index';

// Create a chain that points to the GraphQL endpoint on the same origin
// We'll add auth headers dynamically
export const createGqlClient = (token?: string) => {
  const headers: Record<string, string> = {
    'Content-Type': 'application/json',
  };

  if (token) {
    headers['token'] = `${token}`;
  }

  return Chain('/graphql', { headers });
};

// Default client without auth
export const gql = createGqlClient();
